import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'gopi',
      email: 'gopi@example.com',
      password: bcrypt.hashSync('123'),
      isAdmin: true,
    },
    {
      name: 'George',
      email: 'george@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: "damo",
      email: "damo@gmail.com",
      password: bcrypt.hashSync('123') ,
      isAdmin: true,
    }
  ],
  products: [
    {
  name: "REDMI Note 12 Pro 5G (Glacier Blue, 128 GB)  (6 GB RAM)",
  slug: "phone",
  image: "/images/PHONE0.webp",
  images: [],
  brand: "REDMI",
  category: "PHONE",
  description: "6 GB RAM | 128 GB ROM 16.94 cm (6.67 inch) Full HD+ AMOLED Display 50MP (OIS) + 8MP + 2MP | 16MP Front Camera 5000 mAh Lithium Polymer Battery Mediatek Dimensity 1080 Processor",
  price: 14599,
  countInStock: 50,
  rating: 0,
  numReviews: 0,
  reviews: [],
    },
    {
  name: "APPLE iPhone 13 (Pink, 128 GB)",
  slug: "iphone",
  image: "/images/iphone.webp",
  images: [],
  brand: "APPLE",
  category: "PHONE",
  description: "iPhone 13. boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity. Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension. A big leap in battery life, a durable design, and a bright Super Retina XDR display facilitate boosting your user experience.",
  price: 59699,
  countInStock: 30,
  rating: 0,
  numReviews: 0,
  reviews: [],
    },
    {
      name: "SAMSUNG Galaxy M14 5G (Icy Silver, 128 GB)  (6 GB RAM)",
  slug: "samsung",
  image: "/images/samsung.webp",
  images: [],
  brand: "SAMSUNG",
  category: "PHONE",
  description: "sample d16.72 centimeters (6.6-inch) LCD, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color 50MP+2MP+2MP Triple camera setup- True 50MP (F1.8) main camera + 2MP (F2.4) + 2MP (F2.4)| 13MP (F2.0) front camera Superfast 5G with 13 5G Bands, Powerful Exynos 1330 Octa Core 2.4GH 5nm processor with Letest Android 13,One UI Core 5.0, 6000mAH lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase Get up to 2 times of Android Updates & 4 times of Security Updates with Samsung Galaxy M14 5G.escription",
  price: 22499,
  countInStock: 35,
  rating: 0,
  numReviews: 0,
  reviews: [],
    },
    {
      name: "IQOO Z6 Lite 5G (With Charger) (Mystic Night, 128 GB)",
      slug: "IQOO Z6",
      image: "/images/iq.webp",
      images: [],
      brand: "OPPO",
      category: "PHONE",
      description: "sample descrip6 GB RAM | 128 GB ROM 16.97 cm (6.68 inch) Display 50MP Rear Camera 5000 mAh Batterytion",
      price: 22899,
      countInStock: 40,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "Blue Star Convertible 5 in 1 Cooling 2023 Model 1.5 Ton 3 Star Split Inverter Multi Sensors, Stabalizer Free Operation, Self Diagnosis, Dust Filter AC - White  (IA318FNU, Copper Condenser)",
      slug: "ac",
      image: "/images/ac1.webp",
      images: [],
      brand: "BLUE STAR",
      category: "AC",
      description: "1.5 Ton 3 Star BEE Rating 2023 : For energy savings upto 15% (compared to Non-Inverter 1 Star) Auto Restart: No need to manually reset the settings post power-cut Copper : Energy efficient, best in class cooling with easy maintenance. Sleep Mode: Auto-adjusts the temperature to ensure comfort during your sleep",
      price: 35799,
      countInStock: 15,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "Godrej 5-in-1 Convertible Cooling 2023 Model 1.5 Ton 4 Star Split Inverter with 4 Way Swing and Tri Filtration System AC - White  (EI 18PINV4R32-WWP, Copper Condenser)",
      slug: "AC",
      image: "/images/ac2.webp",
      images: [],
      brand: "GODREJ",
      category: "AC",
      description: "1.5 Ton 4 Star BEE Rating 2023 : For energy savings upto 20% (compared to Non-Inverter 1 Star) Auto Restart: No need to manually reset the settings post power-cut Copper : Energy efficient, best in class cooling with easy maintenance",
      price: 51222,
      countInStock: 5,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "Voltas 1.5 Ton 3 Star Split Inverter AC - White  (183V Vectra Prime(4503447), Copper Condenser)",
      slug: "Ac",
      image: "/images/ac3.webp",
      images: [],
      brand: "VOLTAS",
      category: "AC",
      description: "1.5 Ton 3 Star BEE Rating 2023 : For energy savings upto 15% (compared to Non-Inverter 1 Star) Auto Restart: No need to manually reset the settings post power-cut Copper : Energy efficient, best in class cooling with easy maintenance. Sleep Mode: Auto-adjusts the temperature to ensure comfort during your sleep",
      price: 45899,
      countInStock: 0,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "Voltas 1.5 Ton 5 Star Split Inverter AC - White  (183V Vectra Prime(4503447), Copper Condenser)",
      slug: "ac1",
      image: "/images/ac4.webp",
      images: [],
      brand: "VOLTAS",
      category: "AC",
      description: "1.5 Ton 3 Star BEE Rating 2023 : For energy savings upto 15% (compared to Non-Inverter 1 Star) Auto Restart: No need to manually reset the settings post power-cut Copper : Energy efficient, best in class cooling with easy maintenance. Sleep Mode: Auto-adjusts the temperature to ensure comfort during your sleep",
      price: 29399,
      countInStock: 20,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "USHA ArmorAR1100WB 1100 W Dry Iron  (Purple)",
      slug: "iron",
      image: "/images/iron1.webp",
      images: [],
      brand: "USHA",
      category: "IRON BOX",
      description: "Keep your clothes neat and crisp with the help of the Usha Armor Dry Iron. Thanks to its power consumption of up to 1100 W, this dry iron rapidly heats up to allow you to iron your clothes easily. It has five fabric settings that let you iron a variety of fabrics as per your needs. This dry iron features an indicator lamp that lets you know about its operational status. Moreover, it is made with a Black Weilberger non-stick soleplate that allows you to seamlessly glide it over the fabrics.",
      price: 3999,
      countInStock: 15,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "HAVELLS by Havells Dazzle 1100 W Dry Iron  (Black)",
      slug: "havells",
      image: "/images/iron2.webp",
      images: [],
      brand: "HAVELLS",
      category: "IRON BOX",
      description: "1100W , Aerodynamic design Shock Proof front design , Flexible 360 swivel cord guard , Easy grip temperature control dial , Greblon E2 grade Non-Stick coated sole plate",
      price: 2499,
      countInStock: 20,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "Nova Plus Amaze NI 10 1100 W Dry Iron  (Grey & Turquoise)",
      slug: "nova",
      image: "/images/iron3.webp",
      images: [],
      brand: "NOVA",
      category: "IRON BOX",
      description: "Look stunning and exude confidence in crisp, creaseless clothes with the Nova Plus 1100 W Amaze NI 10 Dry Iron. This home appliance features a Non-stick Triple-coated Soleplate, Quick Heat Technology, and a 360-degree swivel cord for easy and quick ironing of different fabrics and garments.",
      price: 1799,
      countInStock: 10,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "BAJAJ DX 2 600 W Dry Iron  (Black)",
      slug: "Bajaj",
      image: "/images/iron4.webp",
      images: [],
      brand: "BAJAJ",
      category: "IRON BOX",
      description: " Our innovative and comprehensive range of home appliances make life a whole lot easier. Like a helping hand, they are designed to make life comfortable. From irons to water heaters and air coolers to room heaters, every product is made to cater to your unique needs.",
      price: 499,
      countInStock: 0,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "Crompton ACGM - AMEO Ameo 750 Mixer Grinder (3 Jars, Black, Green)",
      slug: "crompton",
      image: "/images/mixer1.webp",
      images: [],
      brand: "CROMPTON",
      category: "MIXER GRINDER",
      description: "Whip up chutneys, grind masalas and prepare yummy shakes effortlessly with the Flipkart Smartbuy Classico 500W Mixer Grinder. This mixer grinder, with its multipurpose jars, makes cooking convenient, less time consuming and fun. It also comes with a powerful 500W overload protected motor which is designed to offer a durable performance",
      price: 3599,
      countInStock: 40,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "V-Guard Citius 750 Watt Juicer Mixer Grinder | 3 Year Motor Warranty | Sturdy QuadraFlow Design Juicer Jar | PrecisionBlend Stainless Steel Blades | 750 Juicer Mixer Grinder (4 Jars, Midnight Blue)",
      slug: "vguard",
      image: "/images/mixer2.webp",
      images: [],
      brand: "V-GUARD",
      category: "MIXER GRINDER",
      description: "Introducing the V-Guard Citius Juicer Mixer Grinder - your perfect kitchen companion for diverse Indian tastes! With a robust 750-watt motor that reaches an impressive speed of 21,000 RPM, this mixer grinder is designed to deliver exceptional performance for all your diverse grinding needs, making your kitchen tasks a breeze. Built to withstand the rigours of a busy Indian kitchen, the V-Guard Citius Mixer Grinder features a powerful 750W SpinMaster motor that undergoes rigorous endurance tests, including a 30-minute grinding test, to ensure it can handle the toughest masalas and chutneys without overheating, ensuring reliable performance for your daily Indian cooking needs. Crafted with durable PrecisionBlend stainless steel blades, this mixer grinder ensures efficient grinding of all your ingredients, from aromatic spices to tough lentils. The detachable blades also make cleaning easy and hassle free. The set of 4 versatile jars, including a chutney jar, dry jar, wet jar and juicer jar, are not only durable but also designed to cater to diverse and varied cooking needs. The innovative juicer jar with a QuadraFlow design provides an advantage over traditional cylindrical jars, allowing for more efficient blending and processing of ingredients. It also helps reduce oxidation and preserve the nutritional value of the ingredients. Equipped with safety features such as non-slip rubber feet for stability, and an impact-resistant ABS body to withstand accidental knocks, bumps, and falls in your kitchen. Upgrade your kitchen with the V-Guard Citius Mixer Grinder and experience the joy of efficiency, durability, and safety in your daily cooking routine. Say goodbye to tedious grinding and hello to hassle-free and flavorful cooking with this powerful and reliable mixer grinder by your side!",
      price: 4449,
      countInStock: 15,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "Flipkart SmartBuy PowerChef Premium 500 W Mixer Grinder#JustHere",
      slug: "mixie",
      image: "/images/mixer3.webp",
      images: [],
      brand: "POWER CHEF",
      category: "MIXER GRINDER",
      description: " Whip up chutneys, grind masalas and prepare yummy shakes effortlessly with the Flipkart Smartbuy Classico 500W Mixer Grinder. This mixer grinder, with its multipurpose jars, makes cooking convenient, less time consuming and fun. It also comes with a powerful 500W overload protected motor which is designed to offer a durable performance.",
      price: 7999,
      countInStock: 0,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
    {
      name: "BAJAJ 410570 GX 1 500 W Juicer Mixer Grinder (3 Jars, Blue)",
      slug: "Mixer",
      image: "/images/mixer4.webp",
      images: [],
      brand: "BAJAJ",
      category: "MIXER GRINDER",
      description: "The Bajaj GX1 Mixer-grinder makes it easy to grind spices, purees, and other ingredients for your favourite recipes. It fulfils a variety of cooking requirements with its three jars of varying capacities. Additionally, the jars include easy-grip handles, adding to the convenience of use. This mixer-grinder functions within a voltage range ,safeguarding its motor from voltage fluctuations while ensuring effective performance. Furthermore, this mixer-grinder's overload protection safeguards this device from damage caused by motor overload.",
      price: 1299,
      countInStock: 15,
      rating: 0,
      numReviews: 0,
      reviews: [],
    },
  ],
};
export default data;
